record LoginData,
  username : String,
  password_md5 : String,
  osu_version : String,
  utc_offset : Int32,
  display_city : Bool,
  adapters_str : String,
  adapters_md5 : String,
  uninstall_md5 : String,
  disk_signature_md5 : String,
  osu_path_md5 : String,
  pm_private : Bool
